repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: check-json
    -   id: double-quote-string-fixer
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
